### ISSUE TITLE
Read and Modify Integrations

### ISSUE THREAD

**Issue by SamuelSaunders** [stitchdata/python-stitch-client#9]
Our stitch integrations were broken by Stitch's recent changes to their BigQuery loader. We now need to recreate multiple integrations. Is it possible to read and modify the integrations through the API to save us manually changing everything though the UI? (official support haven't been able to help) @cmerrick

**Comment by cmerrick** [comment]
Hi @SamuelSaunders - I can't provide any additional help there, sorry. Closing since the question isn't relevant to this repository, contact Stitch support if you have followup questions.
